// <auto-generated />
namespace Web_Ban_Sach.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddMaNCCMaPB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMaNCCMaPB));
        
        string IMigrationMetadata.Id
        {
            get { return "202511110944536_AddMaNCCMaPB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
